version: "3.7"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.0
        container_name: elasticsearch1
        environment:
            - discovery.type=single-node
            - http.cors.enabled=true
            - http.cors.allow-origin=*
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - elasticdata1:/usr/share/elasticsearch/data
        networks:
            - recommender
    kibana:
        depends_on:
            - elasticsearch
        image: docker.elastic.co/kibana/kibana-oss:7.6.0
        ports:
            - 5601:5601
        networks:
            - recommender
    db1:
        image: mongo
        ports:
            - 27017:27017
        networks:
            - recommender
networks:
    recommender:
volumes:
    elasticdata1:
        driver: local
